---
title: "Workspace Orientation"
author: Kris Sankaran
date: 2026-09-01
bibliography: references.bib
format:
  html:
    embed-resources: true
    html-math-method: mathjax
    fig-align: center
execute:
    echo: true
    message: false
    warning: false
    cache: false
    eval: true
---

```{r}
#| label: setup
#| echo: false
library(tidyverse)
theme_set(theme_classic() + theme(panel.border= element_rect(fill = NA, linewidth = .5)))
set.seed(2026)
```

This note describes the development environment we'll use throughout the class.
By the end, you should be able to

    - use quarto notebooks to combine code, visualizations, and commentary.
    - run the pi coding agent to create a ggplot2 visualization
    - rerun code demos using the course codespace

## Notebooks

1. What does a code notebook look like.

2. How is it run.

3. What types of languages it can run

    - how to create an R cell
    - how to create a javascript cell
    - how to create a python cell

4. Why is it useful: rerunning easily

5. Quarto notebooks make it possible to combine visualization code with
commentary within the same plain text file. This is very helpful whenever the
source data might potentially change (either because new data are generated over
time or because mistakes are found and fixed). If the code in our notebook...

6. Why it is useful: compiles into several types of output, including HTML for the web

7. Making the notebooks clean

8. Making the notebook self-contained

## Agentic Coding

9. what is a coding agent, how is it different from using online resource

10. why it's still important to learn: context

11. why it's still important to learn: judgment

## Submissions

12. quarto render

13. embedding resources

14. sharing a server

15. how to do this for the homework

## Codespaces

16. for testing things out in the meantime

17. will eventually want to develop yourself